# Generated by Django 3.0 on 2020-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discription',
            field=models.TextField(default=' there is now discrption for this product.'),
        ),
    ]
